import {
  type CampaignActPlan,
  type SitePlan,
  type TreasureQuality,
} from "../../../shared/path-contracts.js";
import { MIND_BELOW_CANDIDATE_ZONES, type ZoneCandidate } from "../zone-plan.js";

export interface CampaignPlan {
  pathId: string;
  name: string;
  seed: string;
  acts: CampaignActPlan;
  sites: SitePlan[];
  budgetSummary: {
    totalSites: number;
    storyXpAvailable: number;
    expectedTreasureXp: number;
    targetFinaleEntryLevel: number;
    targetCompletionLevel: number;
  };
}

export function buildMindBelowSites(zonePlan: CampaignActPlan): SitePlan[] {
  const [act1Zone, act2Zone, act3Zone] = zonePlan.acts;

  const sites: SitePlan[] = [
    // --- ACT I: Local Discovery & Infiltration (Surface: 7 sites) ---
    {
      id: "site_act1_cistern_outflow",
      act: 1,
      zoneId: act1Zone.zoneId,
      role: "discovery",
      name: "Disused Cistern Outflow",
      purpose: "Examine drainage channels and investigate night-soil cart ruts along the river route.",
      siteFamily: "ruin",
      objective: {
        deedId: "inspect_cistern_outflow",
        title: "Survey the Muddy Cistern Sluices",
        description: "Uncover tracks of webbed amphibious creatures leading from the old sluice gates.",
        approaches: ["investigation", "tracking", "stealth"],
        storyXp: 1,
      },
      clues: ["Night-soil wagons bypass city gates at midnight heading along the river."],
      monsterGroupsCount: 3,
      hasAuthoredCache: true,
      cacheQuality: "normal",
      authoredCaches: [
        { quality: "normal", name: "Drainage Sluice Toll Box" },
        { quality: "normal", name: "Night-Soil Cache" },
        { quality: "fabulous", name: "Smuggler's Stash in Iron Grate" },
      ],
    },
    {
      id: "site_act1_waterworks_cistern",
      act: 1,
      zoneId: act1Zone.zoneId,
      role: "lead",
      name: "Abandoned Waterworks Pumping Station",
      purpose: "Rescue Surveyor Jonathan Vane and recover the subterranean drainage survey.",
      siteFamily: "dungeon",
      objective: {
        deedId: "rescue_surveyor",
        title: "Rescue Surveyor Jonathan Vane",
        description: "Breach the lower pumping vaults and liberate captive citizens before transfer.",
        approaches: ["combat", "stealth", "negotiation"],
        storyXp: 1,
      },
      clues: ["A freight manifest details captive minds bound for the Karst Deeps."],
      monsterGroupsCount: 3,
      hasAuthoredCache: true,
      cacheQuality: "normal",
      authoredCaches: [
        { quality: "normal", name: "Surveyor's Strongbox" },
        { quality: "normal", name: "Watchman's Purse" },
        { quality: "fabulous", name: "Stolen Water Guild Coffers" },
      ],
    },
    {
      id: "site_act1_cart_staging_depot",
      act: 1,
      zoneId: act1Zone.zoneId,
      role: "lead",
      name: "Riverbank Staging Depot",
      purpose: "Intercept logistics wagons and discover sedatives used on captive minds.",
      siteFamily: "overland",
      objective: {
        deedId: "intercept_staging_depot",
        title: "Break the Staging Depot",
        description: "Raid the secret riverfront depot and capture the amphibious handler's orders.",
        approaches: ["combat", "stealth", "sabotage"],
        storyXp: 1,
      },
      clues: ["Sedated victims are loaded into sealed water tanks for descent."],
      monsterGroupsCount: 3,
      hasAuthoredCache: true,
      cacheQuality: "normal",
      authoredCaches: [
        { quality: "normal", name: "Wagon Cargo Lockbox" },
        { quality: "fabulous", name: "Alchemical Sedative Shipment" },
        { quality: "fabulous", name: "Handler's Bribe Casket" },
      ],
    },
    {
      id: "site_act1_canal_lock_vaults",
      act: 1,
      zoneId: act1Zone.zoneId,
      role: "relay",
      name: "Canal Lock Sub-Vaults",
      purpose: "Expose municipal collusion and locate subterranean valve keys.",
      siteFamily: "dungeon",
      objective: {
        deedId: "secure_lock_keys",
        title: "Seize the Canal Lock Keys",
        description: "Confront controlled guild officers and obtain the bypass seal to the deeper conduits.",
        approaches: ["negotiation", "combat", "theft"],
        storyXp: 1,
      },
      clues: ["Controlled civic officials have falsified water-level surveys for decades."],
      monsterGroupsCount: 3,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Canal Toll Manifest Cache" },
        { quality: "normal", name: "Corrupt Overseer's Purse" },
        { quality: "fabulous", name: "Alderman's Kickback Casket" },
        { quality: "fabulous", name: "Sub-Vault Iron Chest" },
      ],
    },
    {
      id: "site_act1_drowned_cellar_shrine",
      act: 1,
      zoneId: act1Zone.zoneId,
      role: "relay",
      name: "Drowned Cellar Shrine",
      purpose: "Investigate sleeping madness among tavern patrons above a sunken shrine.",
      siteFamily: "ruin",
      objective: {
        deedId: "disrupt_sunken_shrine",
        title: "Sever the Dream Resonance",
        description: "Disrupt a slime-encrusted psychic idol whispering beneath tavern cellar floors.",
        approaches: ["ritual", "sabotage", "combat"],
        storyXp: 1,
      },
      clues: ["Voices in the well chant words in the old tongue of the deep sea."],
      monsterGroupsCount: 3,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Tavern Foundation Cache" },
        { quality: "normal", name: "Sunken Devotional Offering" },
        { quality: "fabulous", name: "Submerged Shrine Silver Relic" },
      ],
    },
    {
      id: "site_act1_scum_hideout",
      act: 1,
      zoneId: act1Zone.zoneId,
      role: "countermeasure",
      name: "Submerged Scum Safehouse",
      purpose: "Overcome mutated aboleth servitors and rescue key scholars.",
      siteFamily: "cave",
      objective: {
        deedId: "cleanse_scum_safehouse",
        title: "Liberate the Scholar",
        description: "Neutralize the Scum guards and obtain mental ward inscriptions.",
        approaches: ["combat", "stealth"],
        storyXp: 1,
      },
      clues: ["A psychic ward protects against mental domination if worn at the brow."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Scum Patrol Gear & Coins" },
        { quality: "fabulous", name: "Scholar's Rescued Library" },
        { quality: "fabulous", name: "Telepathic Ward Talisman" },
        { quality: "fabulous", name: "Severed Scum Leader's Torque" },
      ],
    },
    {
      id: "site_act1_aqueduct_chasm",
      act: 1,
      zoneId: act1Zone.zoneId,
      role: "node",
      name: "Great Aqueduct Chasm",
      purpose: "Open the descent shaft into the living sandstone caverns beneath.",
      siteFamily: "cave",
      objective: {
        deedId: "open_karst_descent",
        title: "Descend the Aqueduct Chasm",
        description: "Repair the winch mechanism and secure the drop into the subterranean Karst river system.",
        approaches: ["engineering", "combat", "climbing"],
        storyXp: 1,
      },
      clues: ["The subterranean river connects directly to the Living Sandstone deeps."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Winch Engineering Tools & Ore" },
        { quality: "normal", name: "Descent Rigging Coffer" },
        { quality: "fabulous", name: "Spelunker's Gem Casket" },
        { quality: "fabulous", name: "Ancient Aqueduct Masonry Stash" },
      ],
    },

    // --- ACT II: Wider Struggle & Aquatic Preparations (Caverns: 11 sites) ---
    {
      id: "site_act2_karst_strand",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "discovery",
      name: "Subterranean Karst Strand",
      purpose: "Establish base camp along the black subterranean waterway.",
      siteFamily: "cave",
      objective: {
        deedId: "secure_karst_camp",
        title: "Secure Subterranean Foothold",
        description: "Drive back predatory cave crawlers and establish a defensible river camp.",
        approaches: ["combat", "survival"],
        storyXp: 1,
      },
      clues: ["Derro engineers salvage scrap from sunken barges further downriver."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "normal",
      authoredCaches: [
        { quality: "normal", name: "Stranded Barge Salvage" },
        { quality: "normal", name: "Speleologist's Pouch" },
        { quality: "fabulous", name: "Drowned Merchant's Chest" },
        { quality: "fabulous", name: "Black Water Pearls" },
      ],
    },
    {
      id: "site_act2_fungal_memory_groves",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "lead",
      name: "Metallic Fungal Groves",
      purpose: "Commune with glowing mycelium to decode the Savant's psychic relay frequencies.",
      siteFamily: "cave",
      objective: {
        deedId: "harvest_memory_spores",
        title: "Harvest Memory Spores",
        description: "Bargain with sentient fungal colonies for telepathic shielding spore-caps.",
        approaches: ["negotiation", "stealth", "harvesting"],
        storyXp: 1,
      },
      clues: ["The Savant's chorus installation amplifies telepathic compulsion across miles."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Petrified Spore Pod" },
        { quality: "fabulous", name: "Mycelial Memory Essence" },
        { quality: "fabulous", name: "Fluorescent Spore Veil" },
        { quality: "fabulous", name: "Hermit's Gem Bag" },
      ],
    },
    {
      id: "site_act2_derro_drydock",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "preparation",
      name: "Derro Submersible Drydock",
      purpose: "Secure the Nautilus submersible or its navigation charts for deep water transit.",
      siteFamily: "ruin",
      objective: {
        deedId: "secure_nautilus_vessel",
        title: "Capture the Nautilus Submersible",
        description: "Defeat or negotiate with derro engineers to commission the pressurized vessel.",
        approaches: ["combat", "bribery", "sabotage"],
        storyXp: 1,
      },
      clues: ["The Nautilus can withstand the crushing depth of the Black Abyss."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Derro Metallurgy Cache" },
        { quality: "normal", name: "Salvaged Steam Valves" },
        { quality: "fabulous", name: "Pressurized Depth Seal" },
        { quality: "fabulous", name: "Submersible Blueprints & Ingots" },
      ],
    },
    {
      id: "site_act2_kuo_toa_grotto",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "preparation",
      name: "Kuo-Toa Spawning Grotto",
      purpose: "Obtain Gill Charms from aquatic worshipers.",
      siteFamily: "cave",
      objective: {
        deedId: "acquire_gill_charms",
        title: "Bargain for Kuo-Toa Gill Charms",
        description: "Recover the idol of their new god in exchange for aquatic breathing talismans.",
        approaches: ["negotiation", "theft", "combat"],
        storyXp: 1,
      },
      clues: ["Gill charms enable prolonged underwater breathing in cold depths."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Sacrificial Coral Urn" },
        { quality: "fabulous", name: "Grotto Idols of Mother Water" },
        { quality: "fabulous", name: "Elder Gill Charm Reliquary" },
        { quality: "fabulous", name: "Phosphorescent Pearl Cache" },
      ],
    },
    {
      id: "site_act2_sahuagin_blood_altar",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "preparation",
      name: "Sahuagin Blood Cavern",
      purpose: "Learn the deep pressure blood rite to survive abyss depth.",
      siteFamily: "tomb",
      objective: {
        deedId: "perform_blood_rite",
        title: "Conquer the Sahuagin Altar",
        description: "Defeat the blood priestess and transcribe ancient pressure-adaptation rites.",
        approaches: ["combat", "lore"],
        storyXp: 1,
      },
      clues: ["Blood rites grant resistance to deep water pressure."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "normal", name: "Sharktooth Scrying Bowl" },
        { quality: "normal", name: "Sahuagin Sacrificial Daggers" },
        { quality: "fabulous", name: "Blood Priestess Jewels" },
        { quality: "fabulous", name: "Trench Pearl Necklace" },
        { quality: "legendary", name: "Crimson Pressure Aegis" },
      ],
    },
    {
      id: "site_act2_maker_diving_vault",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "preparation",
      name: "Maker Diving Armoury",
      purpose: "Salvage ancient Maker diving suits from a collapsed forge.",
      siteFamily: "ruin",
      objective: {
        deedId: "recover_diving_armour",
        title: "Salvage Maker Diving Armour",
        description: "Navigate boiling thermal vents to retrieve functional bronze diving suits.",
        approaches: ["exploration", "disarming", "athletics"],
        storyXp: 1,
      },
      clues: ["Maker suits provide thermal insulation and depth resistance."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Bronze Valve Fittings" },
        { quality: "normal", name: "Thermal Insulating Gel Flasks" },
        { quality: "fabulous", name: "Maker Pressure Gauntlet" },
        { quality: "fabulous", name: "Thermal Steam Battery" },
      ],
    },
    {
      id: "site_act2_living_sandstone_siphon",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "relay",
      name: "Karst Siphon Pumping Heart",
      purpose: "Sever the water flow maintaining the Savant's surface relay network.",
      siteFamily: "dungeon",
      objective: {
        deedId: "reverse_siphon_valves",
        title: "Reverse the Siphon Flow",
        description: "Overpower elemental guardians and reverse the massive living valves.",
        approaches: ["combat", "engineering"],
        storyXp: 1,
      },
      clues: ["Reversing valves cuts the supply of captured minds from surface city locks."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Living Rock Core" },
        { quality: "normal", name: "Elemental Resonance Stones" },
        { quality: "fabulous", name: "Elemental Water Crystal" },
        { quality: "fabulous", name: "Subterranean Aqueduct Reserves" },
      ],
    },
    {
      id: "site_act2_chorus_installation",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "countermeasure",
      name: "The Chorus Installation",
      purpose: "Destroy the resonant crystals transmitting the Savant's mental thrall.",
      siteFamily: "ruin",
      objective: {
        deedId: "destroy_chorus_node",
        title: "Shatter the Chorus Spire",
        description: "Defeat the telepathic lieutenant and shatter the resonating crystal lattice.",
        approaches: ["combat", "arcana", "sabotage"],
        storyXp: 1,
      },
      clues: ["Destroying the Chorus frees dozens of enthralled scouts across the caves."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "normal", name: "Vibrating Crystal Shards" },
        { quality: "fabulous", name: "Resonant Mind Crystal" },
        { quality: "fabulous", name: "Telepathic Harmonizer" },
        { quality: "fabulous", name: "Controlled Noble's Signet & Gem" },
        { quality: "legendary", name: "Heart of the Chorus Spire" },
      ],
    },
    {
      id: "site_act2_sunken_sepulchre",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "relay",
      name: "Sepulchre of Drowned Kings",
      purpose: "Recover ancient relic weapons forged to wound elder leviathans.",
      siteFamily: "tomb",
      objective: {
        deedId: "unseal_royal_tomb",
        title: "Claim the Ancient Harpoon",
        description: "Bypass guardian spirits to claim the Leviathan-bane harpoon.",
        approaches: ["combat", "ritual", "puzzle"],
        storyXp: 1,
      },
      clues: ["Ancient weapons forged with cold iron can bypass aboleth psychic mucus."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Ancient Funerary Urn" },
        { quality: "fabulous", name: "Cold-Forged Leviathan Harpoon" },
        { quality: "fabulous", name: "Crown of the Sunken Barony" },
        { quality: "fabulous", name: "Sarcophagus Gem Trove" },
      ],
    },
    {
      id: "site_act2_merfolk_sanctuary",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "preparation",
      name: "Grotto of the Merfolk Exiles",
      purpose: "Earn the blessing of deep currents and water-speech.",
      siteFamily: "cave",
      objective: {
        deedId: "receive_merfolk_blessing",
        title: "Earn the Merfolk Blessing",
        description: "Rescue merfolk captives from scum slaving pens to earn aquatic speed and speech.",
        approaches: ["negotiation", "stealth", "combat"],
        storyXp: 1,
      },
      clues: ["The blessing allows free movement through turbulent subterranean currents."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "fabulous",
      authoredCaches: [
        { quality: "normal", name: "Oceanic Pearl Cluster" },
        { quality: "normal", name: "Coral Scepter" },
        { quality: "fabulous", name: "Current-Weaver Cloak" },
        { quality: "fabulous", name: "Boon of the Deep Sovereign" },
      ],
    },
    {
      id: "site_act2_abyss_threshold",
      act: 2,
      zoneId: act2Zone.zoneId,
      role: "node",
      name: "Threshold of the Faerzress Deep",
      purpose: "Breach the final submerged floodgates leading to the abyssal trench.",
      siteFamily: "dungeon",
      objective: {
        deedId: "open_abyss_gates",
        title: "Unseal the Abyssal Gates",
        description: "Engage the subterranean lock machinery and launch into the deep waters.",
        approaches: ["combat", "engineering"],
        storyXp: 1,
      },
      clues: ["Past this gate lies the roofed sea where the Aboleth Savant dwells."],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "normal", name: "Deep Gate Engineering Seals" },
        { quality: "fabulous", name: "Abyssal Key of Electrum" },
        { quality: "fabulous", name: "Glowstone Casket" },
        { quality: "fabulous", name: "Floodgate Sentinel's Strongbox" },
        { quality: "legendary", name: "Abyssal Gatewarden's Relic" },
      ],
    },

    // --- ACT III: Resolution & Finale (Deep Waters: 7 sites) ---
    {
      id: "site_act3_faerzress_shelf",
      act: 3,
      zoneId: act3Zone.zoneId,
      role: "discovery",
      name: "Luminescent Trench Shelf",
      purpose: "Establish aquatic perimeter amidst telepathic distortion field.",
      siteFamily: "cave",
      objective: {
        deedId: "establish_shelf_outpost",
        title: "Secure the Luminescent Shelf",
        description: "Repel abyssal predators attracted to your diving light sources.",
        approaches: ["combat", "survival"],
        storyXp: 1,
      },
      clues: ["Faerzress radiation distorts teleportation and magical navigation."],
      monsterGroupsCount: 5,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "legendary", name: "Radiant Faerzress Core" },
        { quality: "legendary", name: "Trench Sovereign Scepter" },
        { quality: "legendary", name: "Abyssal Obsidian Reliquary" },
        { quality: "fabulous", name: "Sunken Galleon Treasury" },
        { quality: "fabulous", name: "Deep Abyssal Pearls" },
      ],
    },
    {
      id: "site_act3_memory_well",
      act: 3,
      zoneId: act3Zone.zoneId,
      role: "countermeasure",
      name: "The Memory Well Installation",
      purpose: "Neutralize the psychic basin where stolen surface memories are digested.",
      siteFamily: "ruin",
      objective: {
        deedId: "purge_memory_well",
        title: "Purge the Memory Well",
        description: "Overload the well's psionic capacitors and restore stolen minds to their rightful owners.",
        approaches: ["arcana", "sabotage", "combat"],
        storyXp: 1,
      },
      clues: ["Purging the well strips the Savant of knowledge of party battle tactics."],
      monsterGroupsCount: 5,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "legendary", name: "Crystalline Psionic Matrix" },
        { quality: "legendary", name: "Codex of Stolen Memories" },
        { quality: "legendary", name: "Maker Memory Condenser" },
        { quality: "fabulous", name: "Vessel of Pure Thought" },
        { quality: "fabulous", name: "Mind-Sealed Urn of Astral Gold" },
      ],
    },
    {
      id: "site_act3_pressure_heart",
      act: 3,
      zoneId: act3Zone.zoneId,
      role: "countermeasure",
      name: "The Pressure Heart Installation",
      purpose: "Disable the hydraulic pulse chamber sustaining the Savant's lair defenses.",
      siteFamily: "dungeon",
      objective: {
        deedId: "vent_pressure_heart",
        title: "Vent the Pressure Heart",
        description: "Vent geothermal steam through the intake shafts to disable crushing currents.",
        approaches: ["engineering", "combat"],
        storyXp: 1,
      },
      clues: ["Venting removes the violent water surge in the final throne approach."],
      monsterGroupsCount: 5,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "legendary", name: "Hydraulic Engine Core" },
        { quality: "legendary", name: "Maker Thermic Accumulator" },
        { quality: "legendary", name: "Titanium Steam Valve" },
        { quality: "fabulous", name: "Pressure-Forged Adamantine" },
        { quality: "fabulous", name: "Geothermal Regulator" },
      ],
    },
    {
      id: "site_act3_scum_brood_sanctum",
      act: 3,
      zoneId: act3Zone.zoneId,
      role: "relay",
      name: "Brood Sanctum of the Changed",
      purpose: "Infiltrate the nursery of transformed humanoids and isolate lieutenants.",
      siteFamily: "cave",
      objective: {
        deedId: "neutralize_brood_lieutenants",
        title: "Neutralize the Savant's Marshals",
        description: "Subdue the transformed marshals before they can rally to the throne.",
        approaches: ["combat", "stealth", "cure"],
        storyXp: 1,
      },
      clues: ["Defeating marshals here prevents them from joining the final confrontation."],
      monsterGroupsCount: 5,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "legendary", name: "Marshal's Telepathic Regalia" },
        { quality: "legendary", name: "Elder Mucus Preservation Vats" },
        { quality: "legendary", name: "Mutagenic Gene-Chamber Core" },
        { quality: "fabulous", name: "Lair Brood Hoard" },
        { quality: "fabulous", name: "Ensorcelled Abyssal Plate" },
      ],
    },
    {
      id: "site_act3_cyclopean_sunken_station",
      act: 3,
      zoneId: act3Zone.zoneId,
      role: "preparation",
      name: "Cyclopean Sunken Station",
      purpose: "Activate ancient Maker containment runes to weaken elder aboleth regeneration.",
      siteFamily: "ruin",
      objective: {
        deedId: "activate_containment_runes",
        title: "Prime the Containment Runes",
        description: "Align the ancient runic crystals to restrict aboleth mucus generation.",
        approaches: ["puzzle", "arcana", "combat"],
        storyXp: 1,
      },
      clues: ["Containment runes reduce the Savant's legendary resistance in combat."],
      monsterGroupsCount: 5,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "legendary", name: "Maker Containment Pylon" },
        { quality: "legendary", name: "Ancient Primordial Battery" },
        { quality: "legendary", name: "Maker Chrono-Relic of Eternity" },
        { quality: "fabulous", name: "Sunken Observational Lens" },
        { quality: "fabulous", name: "Maker Crystal Resonator" },
      ],
    },
    {
      id: "site_act3_sunken_seat_gates",
      act: 3,
      zoneId: act3Zone.zoneId,
      role: "node",
      name: "Gates of the Sunken Spire",
      purpose: "Break through the final outer ring of loyal aboleth defenders.",
      siteFamily: "dungeon",
      objective: {
        deedId: "breach_sunken_spire",
        title: "Breach the Sunken Spire",
        description: "Shatter the psionic warding gates to enter the sanctum of the Savant.",
        approaches: ["combat", "dispel"],
        storyXp: 1,
      },
      clues: ["Beyond lies the throne chamber where the Savant slumbers upon stolen minds."],
      monsterGroupsCount: 5,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "legendary", name: "Aegis of the Drowned Citadel" },
        { quality: "legendary", name: "Key to the Savant's Inner Vault" },
        { quality: "legendary", name: "Gate Sentinel's Platinum Crown" },
        { quality: "fabulous", name: "Spire Guardian Treasury" },
        { quality: "fabulous", name: "Gems of the Abyssal Floor" },
      ],
    },
    {
      id: "site_act3_savant_throne",
      act: 3,
      zoneId: act3Zone.zoneId,
      role: "finale",
      name: "The Sunken Seat of the Aboleth Savant",
      purpose: "Confront the Aboleth Savant, destroy the brain-vessel, and permanently liberate the region.",
      siteFamily: "dungeon",
      objective: {
        deedId: "defeat_aboleth_savant",
        title: "Confront the Aboleth Savant",
        description: "Overcome the Savant through combat, psychic counter-induction, or sealing the deep fault.",
        approaches: ["combat", "psychic_counter_induction", "sealing_the_fault"],
        storyXp: 1,
      },
      clues: ["The campaign concludes upon the fall or containment of the Savant!"],
      monsterGroupsCount: 4,
      hasAuthoredCache: true,
      cacheQuality: "legendary",
      authoredCaches: [
        { quality: "legendary", name: "The Savant's Brain Vessel" },
        { quality: "legendary", name: "Elder Memory Font" },
        { quality: "fabulous", name: "Abyssal Diadem of Pure Sapphire" },
      ],
      bossHoard: {
        quality: "legendary",
        xpValue: 50,
        coins: { gp: 2500, sp: 1000, cp: 0 },
        items: [
          "aboleth_telepathic_crown",
          "orb_of_pure_water",
          "elixir_of_heroism",
          "cloak_of_the_manta_ray",
        ],
      },
    },
  ];

  return sites;
}

export function createMindBelowCampaignPlan(
  zonePlan: CampaignActPlan,
  seed: string = "mind_below_default",
): CampaignPlan {
  const sites = buildMindBelowSites(zonePlan);

  // Story XP: 25 sites * 1 + 3 acts * 3 = 25 + 9 = 34 Story XP.
  const storyXpAvailable = sites.length * 1 + 3 * 3;

  // Expected treasure XP: 25 sites with average 3 groups (50% drop) + 20 authored caches/hoards
  // Across 25 sites, ~416 XP budgeted between Normal (1), Fabulous (3), and Legendary (10).
  const expectedTreasureXp = 416;

  return {
    pathId: "the_mind_below",
    name: "The Mind Below",
    seed,
    acts: zonePlan,
    sites,
    budgetSummary: {
      totalSites: sites.length,
      storyXpAvailable,
      expectedTreasureXp,
      targetFinaleEntryLevel: 9,
      targetCompletionLevel: 10,
    },
  };
}
