export const ABILITY_KEYS = ["str", "dex", "con", "int", "wis", "cha"] as const;

export const ANCESTRIES = [
  "Human",
  "Dwarf",
  "Elf",
  "Halfling",
  "Goblin",
  "Orc",
  "Tiefling",
  "Wood Elf",
  "Forest Gnome",
  "Lizardman",
  "Half-Ogre",
  "Deep Gnome",
  "Drow",
  "Kuo-Toa",
  "Derro",
  "Quaggoth",
  "Myconid",
  "Deva",
] as const;

export const CLASSES = [
  { name: "Fighter", hitDie: 8 },
  { name: "Thief", hitDie: 6 },
  { name: "Priest", hitDie: 6 },
  { name: "Wizard", hitDie: 4 },
  { name: "Delver", hitDie: 6 },
  { name: "Ras-Godai", hitDie: 6 },
  { name: "Druid", hitDie: 6 },
  { name: "Alchemist", hitDie: 6 },
  { name: "Sage", hitDie: 4 },
  { name: "Monk", hitDie: 6 },
] as const;

export const HEX_DEFINITIONS = [
  [
    "00",
    0,
    0,
    0,
    "Oakhaven Sanctuary",
    "Fortified Basin",
    0,
    "High Watchtower, Temple of St. Jude, Tavern",
  ],
  [
    "01",
    1,
    0,
    -1,
    "North Pine Pass",
    "Rocky Foothills",
    1,
    "Old Cobblestone Watchpost & Toll Bridge",
  ],
  [
    "02",
    1,
    1,
    -1,
    "Glimmercap Hollow",
    "Enchanted Woods",
    1,
    "Forest Gnome Enclave & Alchemical Market",
  ],
  [
    "03",
    1,
    1,
    0,
    "Whispering Delta",
    "Reed Riverbanks",
    1,
    "Abandoned Fisher Skiffs & Sunken Idol",
  ],
  [
    "04",
    1,
    0,
    1,
    "The Mist Fen",
    "Stagnant Swamp",
    1,
    "Willow Tree Barrow with iron-bound door",
  ],
  [
    "05",
    1,
    -1,
    1,
    "Briar Crags",
    "Bramble Hills",
    1,
    "Goblin Clan Outpost & Spiked Barricade",
  ],
  [
    "06",
    1,
    -1,
    0,
    "The Great Sinkhole",
    "Subterranean Descent",
    2,
    "Descent into the Underdark Karst System",
  ],
  [
    "07",
    2,
    0,
    -2,
    "Crag-Hold",
    "Mountain Ridge",
    2,
    "Half-Ogre & Giant Mercenary Trade Outpost",
  ],
  [
    "08",
    2,
    1,
    -2,
    "Sunken Karst Deeps",
    "Karst Limestone",
    2,
    "Flooded Caverns & Bioluminescent Cave",
  ],
  [
    "09",
    2,
    2,
    -2,
    "The Weeping Bog",
    "Toxic Mire",
    2,
    "Sunken Ziggurat of the Weeping Fish",
  ],
  [
    "10",
    2,
    2,
    -1,
    "The Ashen Waste",
    "Volcanic Ashfield",
    2,
    "Smoldering Fissure & Sulfur Pits",
  ],
  [
    "11",
    2,
    2,
    0,
    "The Drowned Shallows",
    "Coast / Delta",
    2,
    "Kuo-Toa Shoreline Shrine & Pearl Traders",
  ],
  [
    "12",
    2,
    1,
    1,
    "Elderwood Primeval",
    "Ancient Forest",
    2,
    "The Heart-Oak Monolith & Sacred Druid Circle",
  ],
  [
    "13",
    2,
    0,
    2,
    "Spire of Astralis",
    "High Peak",
    3,
    "Ancient High Elf Observatory & Star Arch",
  ],
  [
    "14",
    2,
    -1,
    2,
    "The Shadow Cavern",
    "Abyssal Chasm",
    3,
    "Drow Shadow Outpost & Web Bridges",
  ],
  [
    "15",
    2,
    -2,
    2,
    "The Dead Barrow Mound",
    "Desolate Moor",
    3,
    "Tomb of the First Warlord & Wight Crypt",
  ],
  [
    "16",
    2,
    -2,
    1,
    "Iron Gorge Foundry",
    "Canyon",
    2,
    "Orcish Iron Foundry & Smelter Works",
  ],
  [
    "17",
    2,
    -2,
    0,
    "Obsidian Crags",
    "Razor Rock",
    3,
    "Wyvern Roost & Dragon Glass Quarry",
  ],
  [
    "18",
    2,
    -1,
    -1,
    "The Bleeding Rift",
    "Planar Tear",
    3,
    "Eldritch Void Incursion & Floating Monoliths",
  ],
] as const;

export const MONSTERS = {
  trapdoor_spider: {
    name: "Giant Trapdoor Spider",
    ac: 13,
    hp: 18,
    morale: 7,
    attacks: ["Bite +4 — 1d8+2 piercing; DC 12 CON or paralyzed 1d4 rounds"],
    traits: [
      "Ambush Hunter: advantage while concealed",
      "Web Tether: drag a paralyzed target as a free action",
    ],
    lore: [
      "Digs silk-lined vertical pits and strikes from below.",
      "Ground vibrations can trigger a false strike.",
      "Fire deals double damage.",
      "Its venom can produce knockout draughts or blade poison.",
    ],
  },
  barrow_wight: {
    name: "Barrow Wight",
    ac: 14,
    hp: 26,
    morale: 10,
    attacks: [
      "Bronze Longsword +4 — 1d8+2 slashing",
      "Life Drain +4 — 1d6 necrotic; DC 13 CON or maximum HP reduced",
    ],
    traits: [
      "Resists cold, lightning, and non-magical weapons",
      "Immune to poison and necrotic damage",
    ],
    lore: [
      "Cursed warriors entombed in ancient barrows.",
      "Silver or magical weapons pierce their dried flesh.",
      "Holy water deals 2d6 extra radiant damage.",
      "The dried heart can enchant life-stealing weapons.",
    ],
  },
  owlbear: {
    name: "Owlbear",
    ac: 13,
    hp: 42,
    morale: 9,
    attacks: [
      "Beak +6 — 1d10+4 piercing",
      "Claws +6 — 2d6+4 slashing; both hits trigger 1d8 crushing hug",
    ],
    traits: ["Keen scent and sight", "Territorial apex predator"],
    lore: [
      "A ferocious nocturnal hybrid predator.",
      "Fights to the death to protect its young.",
      "Booming noise or sudden flame forces disadvantaged morale.",
      "Its optical lenses can be worked into night-seeing goggles.",
    ],
  },
} as const;

export const THREAT_VECTORS = [
  ["aboleth", "The Sunken Aboleth Sovereign"],
  ["demon", "The Demon Prince Incursion"],
  ["lich", "The Undying Lich-King"],
] as const;
