import type { EncounterMonster } from "./types.js";

/**
 * Key aliases that map shorthand or legacy monster keys to canonical bestiary IDs.
 */
export const MONSTER_ALIASES: Record<string, string> = {
  giant_spider: "spider_giant",
  spider: "spider_giant",
  wolf: "wolf",
};

/**
 * Reviewed stat-block templates for monsters referenced in Cursed Scroll and core zone tables
 * that are not present in the default 231-entry bestiary JSON.
 * Sources: Shadowdark RPG Core Rules and Cursed Scroll zines 1-6.
 */
export const CUSTOM_MONSTER_TEMPLATES: Record<string, Omit<EncounterMonster, "id">> = {
  // --- Oakhaven Borderlands & Common Core Monsters ---
  bandit: {
    monsterKey: "bandit",
    name: "Bandit",
    currentHp: 4,
    maxHp: 4,
    loreTier: 0,
    level: 1,
    ac: 12,
    morale: 7,
    family: "Humanoid",
    move: "near",
    abilities: { str: 1, dex: 1, con: 0, int: 0, wis: 0, cha: 0 },
    alignment: "C",
    attacks: ["1 shortsword +1 (1d6)", "1 shortbow (far) +1 (1d6)"],
    traits: ["Ambush: Advantage on attacks against surprised targets."],
    lore: [
      "Desperate outlaws and highway robbers haunting wilderness roads.",
      "They flee if their leader falls or morale breaks.",
      "Often maintain hidden supply caches in dead hollow trees.",
      "Carry stolen silver and stolen regional trade goods.",
    ],
  },
  orc: {
    monsterKey: "orc",
    name: "Orc Warrior",
    currentHp: 4,
    maxHp: 4,
    loreTier: 0,
    level: 1,
    ac: 15,
    morale: 8,
    family: "Humanoid",
    move: "near",
    abilities: { str: 2, dex: 0, con: 1, int: -1, wis: 0, cha: -1 },
    alignment: "C",
    attacks: ["1 greataxe +2 (1d8)"],
    traits: ["Bloodrage: +1 to hit and damage when below half HP."],
    lore: [
      "Tusked, rugged raiders and iron prospectors claiming highland ridges.",
      "Respect strength, ironwork, and single combat.",
      "Trained war beasts often accompany hunting parties.",
      "Their heavy greataxes are forged with distinctive jagged notches.",
    ],
  },
  skeleton: {
    monsterKey: "skeleton",
    name: "Skeleton",
    currentHp: 4,
    maxHp: 4,
    loreTier: 0,
    level: 1,
    ac: 13,
    morale: 12,
    family: "Undead",
    move: "near",
    abilities: { str: 0, dex: 1, con: 0, int: -2, wis: 0, cha: -2 },
    alignment: "C",
    attacks: ["1 shortsword +1 (1d6)", "1 shortbow (far) +1 (1d6)"],
    traits: [
      "Undead: Immune to morale checks, poison, disease, and cold.",
      "Brittle: Vulnerable to bludgeoning damage (double damage).",
    ],
    lore: [
      "Animated skeletal remains of ancient warriors or sacrificed victims.",
      "Never retreat; fight relentlessly until shattered.",
      "Bludgeoning weapons smash their fragile bones with ease.",
      "Can be turned by holy priests invoking righteous deities.",
    ],
  },
  barrow_wight: {
    monsterKey: "barrow_wight",
    name: "Barrow Wight",
    currentHp: 26,
    maxHp: 26,
    loreTier: 0,
    level: 3,
    ac: 14,
    morale: 10,
    family: "Undead",
    move: "near",
    abilities: { str: 2, dex: 1, con: 2, int: 1, wis: 1, cha: 1 },
    alignment: "C",
    attacks: [
      "1 bronze longsword +4 (1d8+2)",
      "1 life drain +4 (1d6 necrotic, DC 13 CON or max HP reduced)",
    ],
    traits: [
      "Resistant to cold, non-magical weapons, and necrotic damage.",
      "Immune to poison and disease.",
    ],
    lore: [
      "Cursed warriors entombed in primordial earthen barrows.",
      "Their touch leeches the vital life force and warmth from the living.",
      "Silver and magical blades bypass their thick, withered hides.",
      "Their withered hearts can be harvested to enchant life-stealing relics.",
    ],
  },
  wolf: {
    monsterKey: "wolf",
    name: "Wolf",
    currentHp: 6,
    maxHp: 6,
    loreTier: 0,
    level: 1,
    ac: 12,
    morale: 7,
    family: "Beast",
    move: "near",
    abilities: { str: 1, dex: 2, con: 1, int: -3, wis: 1, cha: -2 },
    alignment: "N",
    attacks: ["1 bite +2 (1d6; DC 11 STR or knocked prone)"],
    traits: ["Pack Tactics: Advantage on attack rolls if an ally is adjacent to target."],
    lore: [
      "Wild canine pack hunters roaming the woods and foothills.",
      "Circle weak or isolated prey before striking in unison.",
      "Fear bright torches and open flames.",
      "Thick winter pelts can be harvested and sold for 1 gp.",
    ],
  },

  // --- The Gloaming (CS1) ---
  howler: {
    monsterKey: "howler",
    name: "Howler",
    currentHp: 5,
    maxHp: 5,
    loreTier: 0,
    level: 1,
    ac: 12,
    morale: 7,
    family: "Humanoid",
    move: "near",
    abilities: { str: -1, dex: 2, con: 1, int: 0, wis: 1, cha: -1 },
    alignment: "C",
    attacks: ["1 sling (far) +2 (1d4)", "1 club +1 (1d4)"],
    traits: [
      "Pack Scavenger: Halfling pack that jabbers and shrieks in coyote-pelt cloaks.",
      "Skulker: Advantage on stealth in barrows and mistwood.",
    ],
    lore: [
      "Feral, child-sized halfling scavengers dressed in scraggly coyote pelts.",
      "Haunt the decaying chambers of Bittermold Keep and marsh margins.",
      "Addicted to strange alchemical mushrooms that cause wild shrieking.",
      "Can be bribed or distracted with fresh raw fish and shiny copper.",
    ],
  },

  // --- The Djurum / Red Sands (CS2) ---
  ras_godai: {
    monsterKey: "ras_godai",
    name: "Ras Godai Raider",
    currentHp: 9,
    maxHp: 9,
    loreTier: 0,
    level: 2,
    ac: 13,
    morale: 8,
    family: "Humanoid",
    move: "near",
    abilities: { str: 2, dex: 1, con: 1, int: 0, wis: 1, cha: 0 },
    alignment: "N",
    attacks: ["1 curved scimitar +2 (1d6)", "1 composite bow (far) +2 (1d6)"],
    traits: ["Desert Born: Immune to heat exhaustion and navigates sand dunes without penalty."],
    lore: [
      "Veiled desert nomads defending caravan corridors and hidden rock cisterns.",
      "Honor ancient oasis oaths; hospitable to those who exchange clean salt and water.",
      "Expert camel riders and skirmishers who strike and vanish into dust clouds.",
      "Carry intricate bronze talisman compasses tuned to natural groundwater.",
    ],
  },
  siruul: {
    monsterKey: "siruul",
    name: "Siruul Elf Ranger",
    currentHp: 8,
    maxHp: 8,
    loreTier: 0,
    level: 2,
    ac: 14,
    morale: 8,
    family: "Humanoid",
    move: "near",
    abilities: { str: 0, dex: 3, con: 0, int: 1, wis: 2, cha: 0 },
    alignment: "N",
    attacks: ["1 sun-bow (far) +3 (1d6)", "1 dueling rapier +2 (1d8)"],
    traits: ["Mirage Step: Can disengage as a free action in desert light."],
    lore: [
      "Sun-hardened desert elves with copper hair and flowing silk wraps.",
      "Master archers and fencing instructors respected from Alkesh to Meridia.",
      "Guard secret sandstone tombs and ancient solar obelisks.",
      "Their silk veils filter sand and preserve moisture in severe heat.",
    ],
  },

  // --- The Isles of Andrik (CS3) ---
  draugr: {
    monsterKey: "draugr",
    name: "Draugr Sea-Corpse",
    currentHp: 11,
    maxHp: 11,
    loreTier: 0,
    level: 2,
    ac: 13,
    morale: 12,
    family: "Undead",
    move: "near (swim)",
    abilities: { str: 2, dex: 0, con: 2, int: -1, wis: 0, cha: -2 },
    alignment: "C",
    attacks: ["1 rusted broadaxe +2 (1d8)", "1 drowning grip +2 (1d6 bludgeoning)"],
    traits: [
      "Undead: Immune to morale, cold, poison.",
      "Waterborne: Swims without breath; rises from sea caves at low tide.",
    ],
    lore: [
      "Waterlogged corpses of drowned norsemen seeking vengeance on the living.",
      "Guard sunken longships and sea barrows along icy fjord cliffs.",
      "Vulnerable to fire and consecrated runic iron.",
      "Their salt-encrusted talismans still gleam with old silver coins.",
    ],
  },
  dverg: {
    monsterKey: "dverg",
    name: "Dverg Runesmith",
    currentHp: 10,
    maxHp: 10,
    loreTier: 0,
    level: 2,
    ac: 15,
    morale: 9,
    family: "Humanoid",
    move: "near",
    abilities: { str: 2, dex: 0, con: 2, int: 1, wis: 1, cha: -1 },
    alignment: "N",
    attacks: ["1 forged warhammer +3 (1d8)", "1 throwing hammer (near) +2 (1d6)"],
    traits: ["Rune-Hardened: Advantage on saves against spells and magic."],
    lore: [
      "Stout northern mountain craftsmen dwelling beneath glaciers and crags.",
      "Master smiths of enchanted chainmail and whalebone carvings.",
      "Will trade forged gear for rare ores, mead, and whale oil.",
      "Hold deep grudges against sea wolves who violate sworn harbor treaties.",
    ],
  },
  nord: {
    monsterKey: "nord",
    name: "Nord Raider",
    currentHp: 5,
    maxHp: 5,
    loreTier: 0,
    level: 1,
    ac: 13,
    morale: 8,
    family: "Humanoid",
    move: "near",
    abilities: { str: 2, dex: 1, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: "N",
    attacks: ["1 barbed spear +2 (1d6)", "1 round shield bash +2 (1d4)"],
    traits: ["Sea-Legs: Immune to balance penalties aboard rocking longships."],
    lore: [
      "Hardy northern island raiders and seal hunters.",
      "Bound by solemn oath-rings and loyalty to their jarl.",
      "Value bravery, poetry, and shared mead in coastal longhouses.",
      "Carry carved walrus-ivory amulets that ward against freezing spray.",
    ],
  },

  // --- River of Night (CS4) ---
  basilisk_cultists: {
    monsterKey: "basilisk_cultists",
    name: "Basilisk Cultist",
    currentHp: 4,
    maxHp: 4,
    loreTier: 0,
    level: 1,
    ac: 11,
    morale: 8,
    family: "Humanoid",
    move: "near",
    abilities: { str: 0, dex: 1, con: 1, int: 1, wis: 0, cha: 0 },
    alignment: "C",
    attacks: ["1 obsidian dagger +1 (1d4 + poison; DC 11 CON or 1d4 damage)"],
    traits: ["Stone-Gaze Devotion: Advantage on saves against petrification."],
    lore: [
      "Fanatical worshippers of the primordial serpent and basilisk broods.",
      "Lurk in overgrown stepped ziggurats along the Black River.",
      "Coat their ritual blades in venom milked from young basilisk hatchlings.",
      "Adorn their bodies with green serpentine tattoos and jade nose-plugs.",
    ],
  },
  jaguar_king: {
    monsterKey: "jaguar_king",
    name: "Jaguar King",
    currentHp: 22,
    maxHp: 22,
    loreTier: 0,
    level: 4,
    ac: 14,
    morale: 9,
    family: "Beast",
    move: "near (climb)",
    abilities: { str: 3, dex: 3, con: 2, int: -1, wis: 2, cha: 1 },
    alignment: "N",
    attacks: ["2 claws +4 (1d6)", "1 bite +4 (1d8)"],
    traits: [
      "Canopy Stalker: Can move through jungle canopy without touching the ground.",
      "Pounce: If it hits with both claws, the target is knocked prone.",
    ],
    lore: [
      "Massive, emerald-eyed apex feline revered by riverside tribes.",
      "Hunts solitary travelers from high canopy boughs.",
      "Its pelt is sought by shamans for powerful spirit-warding cloaks.",
      "Avoids fire and loud explosive concussions.",
    ],
  },

  // --- Morzomotha & Karst Deeps (CS5) ---
  nuln: {
    monsterKey: "nuln",
    name: "Nuln Shadow-Stalker",
    currentHp: 14,
    maxHp: 14,
    loreTier: 0,
    level: 3,
    ac: 13,
    morale: 8,
    family: "Monstrosity",
    move: "near (climb)",
    abilities: { str: 2, dex: 3, con: 1, int: 0, wis: 2, cha: -2 },
    alignment: "C",
    attacks: ["2 shadow claws +3 (1d6)"],
    traits: [
      "Light Blindness: Disadvantage on attack rolls in bright sunlight or torchlight.",
      "Shadow Melding: Invisible in total darkness.",
    ],
    lore: [
      "Gaunt, six-limbed cave predators stalking the sunless vaults of Morzomotha.",
      "Navigate by echolocation and thermal vibrations.",
      "Bright torchlight disorients them and forces morale checks.",
      "Their silk glands yield ultra-light descent ropes.",
    ],
  },
  troglodyte: {
    monsterKey: "troglodyte",
    name: "Troglodyte",
    currentHp: 9,
    maxHp: 9,
    loreTier: 0,
    level: 2,
    ac: 12,
    morale: 7,
    family: "Humanoid",
    move: "near",
    abilities: { str: 1, dex: 1, con: 2, int: -1, wis: 0, cha: -2 },
    alignment: "C",
    attacks: ["2 claws +2 (1d4)", "1 bite +2 (1d4)"],
    traits: [
      "Stench: Any creature starting its turn within close must pass DC 11 CON or have disadvantage on attacks for 1 round.",
      "Chameleon Skin: Advantage on stealth checks in stone caverns.",
    ],
    lore: [
      "Subterranean reptilian humanoids inhabiting damp karst sinkholes.",
      "Emit a nauseating musk when agitated or hunting.",
      "Raid surface camps at night for metal tools and fresh food.",
      "Trade blind cave fish and fungus wine with deep delvers.",
    ],
  },

  // --- City of Masks / Meridia (CS6) ---
  duelist: {
    monsterKey: "duelist",
    name: "Meridian Duelist",
    currentHp: 9,
    maxHp: 9,
    loreTier: 0,
    level: 2,
    ac: 14,
    morale: 8,
    family: "Humanoid",
    move: "near",
    abilities: { str: 0, dex: 3, con: 0, int: 1, wis: 0, cha: 2 },
    alignment: "N",
    attacks: ["1 fine rapier +3 (1d8+1)", "1 parrying main-gauche +2 (1d4)"],
    traits: ["Riposte: Once per combat, make a free melee counterattack when missed."],
    lore: [
      "Flamboyant masked swordsmen fighting honor duels on moonlit marble bridges.",
      "Belong to rival fencing academies such as Flashing Steel and Tiborian's.",
      "Never refuse a formal challenge delivered with a silver token.",
      "Their feathered masks and velvet doublets fetch high prices in pawn shops.",
    ],
  },
  roustabout: {
    monsterKey: "roustabout",
    name: "Canal Roustabout",
    currentHp: 5,
    maxHp: 5,
    loreTier: 0,
    level: 1,
    ac: 11,
    morale: 7,
    family: "Humanoid",
    move: "near",
    abilities: { str: 2, dex: 0, con: 1, int: -1, wis: 0, cha: 0 },
    alignment: "N",
    attacks: ["1 heavy belaying pin +2 (1d6)", "1 brawling fist +2 (1d4)"],
    traits: ["Canal Brawler: +1 damage when fighting on boats or dockside piers."],
    lore: [
      "Tough dockhands, gondoliers, and barge-haulers working Meridia's waterways.",
      "Drink bitter ale in waterfront taverns and gamble on cockfights.",
      "Know every secret watergate, canal shortcut, and sunken cargo cache.",
      "Can be hired as rowers or brawn for 1 gp per day.",
    ],
  },
  bard: {
    monsterKey: "bard",
    name: "College Bard",
    currentHp: 7,
    maxHp: 7,
    loreTier: 0,
    level: 2,
    ac: 12,
    morale: 7,
    family: "Humanoid",
    move: "near",
    abilities: { str: -1, dex: 2, con: 0, int: 2, wis: 1, cha: 3 },
    alignment: "L",
    attacks: ["1 rapier +2 (1d8)", "1 charm song (near; DC 12 CHA or enthralled)"],
    traits: ["Inspire: Allies within near gain +1 to hit on their next turn."],
    lore: [
      "Scholars and balladeers trained in the sunlit halls of the Bardic College.",
      "Collect folklore, ancestral genealogies, and political secrets across districts.",
      "Protected by ancient ducal decrees from arbitrary arrest while performing.",
      "Carry lutes inlaid with mother-of-pearl and secret compartment scrolls.",
    ],
  },
  necromancer: {
    monsterKey: "necromancer",
    name: "Plague Cultist Necromancer",
    currentHp: 12,
    maxHp: 12,
    loreTier: 0,
    level: 3,
    ac: 11,
    morale: 8,
    family: "Humanoid",
    move: "near",
    abilities: { str: -1, dex: 1, con: 1, int: 3, wis: 1, cha: 0 },
    alignment: "C",
    attacks: ["1 bone stave +1 (1d6)", "2 death bolt (near) +3 (1d6 necrotic)"],
    traits: ["Animate Dead: Once per encounter, raise 1d4 skeletons from nearby remains."],
    lore: [
      "Zealots of 'She Who Weeps' practicing forbidden rites in the catacombs.",
      "Wear weeping porcelain masks and robes stained with grave-soil.",
      "Seek to spread pestilence through the lower canal tenements.",
      "Carry vials of virulent plague bile and silver ceremonial scalpels.",
    ],
  },
  assassin: {
    monsterKey: "assassin",
    name: "Shroud Assassin",
    currentHp: 13,
    maxHp: 13,
    loreTier: 0,
    level: 3,
    ac: 13,
    morale: 8,
    family: "Humanoid",
    move: "near",
    abilities: { str: 0, dex: 3, con: 1, int: 1, wis: 1, cha: 1 },
    alignment: "C",
    attacks: [
      "2 poisoned daggers +3 (1d4 + poison; DC 12 CON or 1d6 poison damage)",
      "1 hand crossbow (near) +3 (1d6 + poison)",
    ],
    traits: ["Shadow Step: Advantage on attacks from concealment; double damage on surprise."],
    lore: [
      "Covert operatives of The Shroud executing political contracts in the shadows.",
      "Wear blank black silk masks and communicate using silent finger cant.",
      "Coat their fine stiletto blades with paralyzing nightshade venom.",
      "Carry forged identity papers and skeleton keys to noble estates.",
    ],
  },
  thief: {
    monsterKey: "thief",
    name: "Rooftop Thief",
    currentHp: 4,
    maxHp: 4,
    loreTier: 0,
    level: 1,
    ac: 13,
    morale: 7,
    family: "Humanoid",
    move: "near (climb)",
    abilities: { str: 0, dex: 2, con: 0, int: 1, wis: 0, cha: 1 },
    alignment: "C",
    attacks: ["1 shortsword +2 (1d6)", "1 throwing knife (near) +2 (1d4)"],
    traits: ["Rooftop Acrobat: Half damage from falls; climbs walls at full move speed."],
    lore: [
      "Footpads and cutpurses leaping across the slate roofs of The Rooks.",
      "Wear gray crow masks and soft deerskin boots.",
      "Quick to bargain or reveal guild rumors in exchange for their freedom.",
      "Their pockets contain lockpicks, loaded dice, and cut gemstone shards.",
    ],
  },
  guard: {
    monsterKey: "guard",
    name: "Meridia City Guard",
    currentHp: 5,
    maxHp: 5,
    loreTier: 0,
    level: 1,
    ac: 14,
    morale: 8,
    family: "Humanoid",
    move: "near",
    abilities: { str: 1, dex: 0, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: "L",
    attacks: ["1 halberd +2 (1d8)", "1 heavy crossbow (far) +1 (1d8)"],
    traits: ["Arrest: DC 11 STR check on hit or target is restrained."],
    lore: [
      "Uniformed wardens of the Duke patrolling the grand plazas and marble bridges.",
      "Wear enameled lion-crested half-masks and polished breastplates.",
      "Arrive in squads of 1d6 within 1d4 rounds of alarm horns sounding.",
      "Can be bribed or influenced with official ducal seals.",
    ],
  },
  wererat: {
    monsterKey: "wererat",
    name: "Wererat",
    currentHp: 14,
    maxHp: 14,
    loreTier: 0,
    level: 3,
    ac: 12,
    morale: 8,
    family: "Lycanthrope",
    move: "near (climb, swim)",
    abilities: { str: 1, dex: 2, con: 1, int: 1, wis: 0, cha: -1 },
    alignment: "C",
    attacks: [
      "1 bite +3 (1d4 + curse; DC 12 CON or contract wererat curse)",
      "1 rusty shortsword +3 (1d6)",
    ],
    traits: [
      "Silver Vulnerability: Immune to non-silver, non-magical weapon damage.",
      "Rat Telepathy: Can command giant rats and rat swarms within near.",
    ],
    lore: [
      "Cursed shapechangers lurking in the flooded sewers beneath Rilken Row.",
      "Run smuggling rings, black-market pawn shops, and information brokering.",
      "Only silver weapons or fire can pierce their supernatural regenerative hide.",
      "Their rat nests often hoard antique gold watches and stamped guild tokens.",
    ],
  },
};

/**
 * Resolves a monster key against the static bestiary lookup, alias map, and custom templates.
 */
export function resolveMonsterEntry(
  key: string,
  primaryLookup: (k: string) => EncounterMonster | undefined,
): EncounterMonster | undefined {
  const found = primaryLookup(key);
  if (found) return found;

  const alias = MONSTER_ALIASES[key];
  if (alias) {
    const aliased = primaryLookup(alias);
    if (aliased) return aliased;
  }

  const template = CUSTOM_MONSTER_TEMPLATES[key] ?? (alias ? CUSTOM_MONSTER_TEMPLATES[alias] : undefined);
  if (template) {
    return {
      id: 0,
      ...template,
    };
  }

  return undefined;
}
