/**
 * Single source of truth for Socket.IO event names, imported by both the
 * server (src/server/app.ts) and the client (src/client/*.tsx). Prevents the
 * event-name drift that comes from hardcoding the same string literal on
 * both sides of the wire.
 */
export const EVENTS = {
  CAMP_OPEN: "camp:open",
  CAMP_RESOLVE: "camp:resolve",
  CAMP_SUBMIT_DUTY: "camp:submit_duty",
  CAMPAIGN_COMPLICATION: "campaign:complication",
  CAMPAIGN_SET_CALLER: "campaign:set_caller",
  CAMPAIGN_START: "campaign:start",
  CHARACTER_CHOICE: "character:choice",
  CHARACTER_CREATE: "character:create",
  CHARACTER_DELETE: "character:delete",
  CHARACTER_HP: "character:hp",
  CHARACTER_LEVEL_UP: "character:level_up",
  CHARACTER_RESOURCE: "character:resource",
  CHARACTER_SPELL_AVAILABLE: "character:spell_available",
  CHARACTER_TALENT_ROLL: "character:talent_roll",
  CHARACTER_XP: "character:xp",
  COMBAT_DEATH_SAVE: "combat:death_save",
  COMBAT_END: "combat:end",
  COMBAT_MORALE_CHECK: "combat:morale_check",
  COMBAT_NEXT_TURN: "combat:next_turn",
  COMBAT_REVEAL_AC: "combat:reveal_ac",
  COMBAT_SET_INITIATIVE: "combat:set_initiative",
  COMBAT_SET_SEATING: "combat:set_seating",
  COMBAT_SET_WINNER: "combat:set_winner",
  COMBAT_START: "combat:start",
  COMBAT_TOGGLE_CONDITION: "combat:toggle_condition",
  COMBAT_UPDATE_HP: "combat:update_hp",
  DICE_ROLL: "dice:roll",
  DUNGEON_CLAIM_TREASURE: "dungeon:claim_treasure",
  DUNGEON_DISARM_TRAP: "dungeon:disarm_trap",
  DUNGEON_GENERATE: "dungeon:generate",
  DUNGEON_INTERACT_DOOR: "dungeon:interact_door",
  DUNGEON_LIGHT_TORCH: "dungeon:light_torch",
  DUNGEON_MOVE_ROOM: "dungeon:move_room",
  DUNGEON_RECORD_OUTCOME: "dungeon:record_outcome",
  DUNGEON_RECRUIT_RESCUED: "dungeon:recruit_rescued",
  DUNGEON_SPOT_TRAP: "dungeon:spot_trap",
  ENCOUNTER_FLEE: "encounter:flee",
  ENCOUNTER_HP: "encounter:hp",
  ENCOUNTER_LORE: "encounter:lore",
  ENCOUNTER_MORALE: "encounter:morale",
  ENCOUNTER_RESOLVE: "encounter:resolve",
  ENCOUNTER_START: "encounter:start",
  EXPEDITION_CAMP: "expedition:camp",
  EXPEDITION_CAMP_NIGHT: "expedition:camp_night",
  EXPEDITION_FORAGE: "expedition:forage",
  EXPEDITION_FORCE_MARCH: "expedition:force_march",
  EXPEDITION_SELECT_OBJECTIVE: "expedition:select_objective",
  QUEST_LOG_ADD: "quest_log:add",
  QUEST_LOG_REMOVE: "quest_log:remove",
  HEX_REGENERATE: "hex:regenerate",
  HEX_REVEAL: "hex:reveal",
  HEX_SEARCH: "hex:search",
  HOST_CORRECT: "host:correct",
  INVENTORY_ADD: "inventory:add",
  INVENTORY_DROP: "inventory:drop",
  INVENTORY_EQUIP: "inventory:equip",
  INVENTORY_UNEQUIP: "inventory:unequip",
  NOTE_ADD: "note:add",
  NOTES_PAGE: "notes:page",
  NPC_GENERATE: "npc:generate",
  NPC_RECORD: "npc:record",
  NPC_UPDATE_DISPOSITION: "npc:update_disposition",
  ORACLE_BINARY: "oracle:binary",
  ORACLE_REACTION: "oracle:reaction",
  PARTY_MUSTER: "party:muster",
  PARTY_REST: "party:rest",
  PATH_ENCOUNTERS_ARRIVE: "path_encounters:arrive",
  PATH_ENCOUNTERS_INTERACT: "path_encounters:interact",
  PATH_ENCOUNTERS_READ: "path_encounters:read",
  PATH_ENCOUNTERS_START: "path_encounters:start",
  PHASE_TRANSITION: "phase:transition",
  PRESSURE_ADD: "pressure:add",
  PRESSURE_ADVANCE: "pressure:advance",
  PRESSURE_RESOLVE: "pressure:resolve",
  PRIEST_PENANCE: "priest:penance",
  RETAINER_HIRE: "retainer:hire",
  ROLL_CONTEXTUAL: "roll:contextual",
  ROLLS_PAGE: "rolls:page",
  ROSTER_SELECT_ACTIVE: "roster:select_active",
  SESSION_AWARD_XP: "session:award_xp",
  SESSION_RETURN_SANCTUARY: "session:return_sanctuary",
  SETTLEMENT_GENERATE: "settlement:generate",
  SITE_DISCOVER: "site:discover",
  SITE_ENTER: "site:enter",
  SITE_EXIT: "site:exit",
  SITE_RESOLVE_DEED: "site:resolve_deed",
  SPELLS_RESTORE: "spells:restore",
  TABLE_READY: "table:ready",
  TAVERN_OPEN: "tavern:open",
  TAVERN_RESOLVE: "tavern:resolve",
  TAVERN_SUBMIT_CHOICE: "tavern:submit_choice",
  TRAVEL_MOVE: "travel:move",
  TREASURE_ALLOCATE: "treasure:allocate",
  TREASURE_GENERATE: "treasure:generate",
  WILDERNESS_WATCH: "wilderness:watch",
  ZONE_ENTER: "zone:enter",
  ZONE_EXIT: "zone:exit",

  // Server → client (push)
  STATE: "state",
  ROLL_APPENDED: "roll:appended",
  NOTE_APPENDED: "note:appended",
  TABLE_PRESENCE: "table:presence",
} as const;

/** How long the table host can be disconnected before players are told the
 * host connection may be gone for good. Unlike a lobby-based app, ash-rpg
 * persists campaign state in SQLite regardless of who's connected, so this
 * never destroys anything — it's purely an informational signal. */
export const HOST_GRACE_MS = 5 * 60 * 1000;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];
