import { readFileSync, writeFileSync } from "node:fs";

/**
 * Regenerates src/shared/tarot-deck.ts from data/oracles/tarot-cards.json.
 * The source deck comes from the Pleb Generator's cards.json.
 *
 * npx tsx scripts/ingest/extract-tarot.ts
 */

const FACETS = ["person", "creature_or_trap", "place", "treasure", "situation"] as const;

interface SourceCard {
  title: string;
  description: string;
  upright_meaning: Record<string, string>;
  reversed_meaning: Record<string, string>;
}

const SOURCE = "data/oracles/tarot-cards.json";
const OUTPUT = "src/shared/tarot-deck.ts";

const cards: SourceCard[] = JSON.parse(readFileSync(SOURCE, "utf8"));
if (!Array.isArray(cards) || cards.length === 0) {
  throw new Error(`${SOURCE} did not contain a non-empty array of cards`);
}
for (const card of cards) {
  for (const meaning of ["upright_meaning", "reversed_meaning"] as const) {
    for (const facet of FACETS) {
      if (typeof card[meaning]?.[facet] !== "string") {
        throw new Error(`Card "${card.title}" is missing ${meaning}.${facet}`);
      }
    }
  }
}

/** The source text carries PDF line-break hyphens ("recog- nize"); rejoin them. */
const clean = (value: string): string => value.replace(/([a-z])- ([a-z])/g, "$1$2");
const esc = (value: string): string => JSON.stringify(clean(value));
const lines: string[] = [
  "// Auto-generated by scripts/ingest/extract-tarot.ts from data/oracles/tarot-cards.json. Do not edit.",
  "/**",
  " * The deck read alongside a generated site: one card, upright or reversed, whose",
  " * facets slant the site's context. A reading is a suggestion for the table to",
  " * interpret, never a mechanical result.",
  " */",
  `export const TAROT_FACETS = [${FACETS.map(esc).join(", ")}] as const;`,
  "export type TarotFacet = typeof TAROT_FACETS[number];",
  'export type TarotOrientation = "upright" | "reversed";',
  "",
  "export interface TarotCard {",
  "  /** Stable id: the title lowercased. */",
  "  id: string;",
  "  title: string;",
  "  description: string;",
  "  upright: Record<TarotFacet, string>;",
  "  reversed: Record<TarotFacet, string>;",
  "}",
  "",
  "export const TAROT_DECK: TarotCard[] = [",
];
for (const card of cards) {
  lines.push("  {");
  lines.push(`    id: ${esc(card.title.toLowerCase())},`);
  lines.push(`    title: ${esc(card.title)},`);
  lines.push(`    description: ${esc(card.description)},`);
  for (const [key, source] of [["upright", "upright_meaning"], ["reversed", "reversed_meaning"]] as const) {
    lines.push(`    ${key}: {`);
    for (const facet of FACETS) lines.push(`      ${facet}: ${esc(card[source][facet])},`);
    lines.push("    },");
  }
  lines.push("  },");
}
lines.push("];", "");

writeFileSync(OUTPUT, lines.join("\n"), "utf8");
console.log(`Wrote ${cards.length} cards to ${OUTPUT}`);
